/* Generated by MyraPad at 2/11/2023 8:32:46 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace WakaSkies.Desktop.UI
{
	partial class BackgroundSelectClosed: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Background";
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			openBackground = new TextButton();
			openBackground.Text = "Open";
			openBackground.Padding = new Thickness(3);
			openBackground.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			openBackground.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			openBackground.GridColumn = 1;
			openBackground.Id = "openBackground";

			
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Width = 400;
			Height = 40;
			Padding = new Thickness(5);
			Opacity = 0.75f;
			Background = new SolidBrush("#252526FF");
			Id = "backgroundSelectGridClosed";
			Widgets.Add(label1);
			Widgets.Add(openBackground);
		}

		
		public TextButton openBackground;
	}
}
