/* Generated by MyraPad at 1/28/2023 9:06:11 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace WakaSkies.Desktop.UI
{
	partial class Icons: Panel
	{
		private void BuildUI()
		{
			homeButton = new ImageButton();
			homeButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("home.png");
			homeButton.ImageWidth = 40;
			homeButton.ImageHeight = 40;
			homeButton.Margin = new Thickness(10);
			homeButton.Padding = new Thickness(5);
			homeButton.Id = "homeButton";

			downloadButton = new ImageButton();
			downloadButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("download.png");
			downloadButton.ImageWidth = 40;
			downloadButton.ImageHeight = 40;
			downloadButton.Margin = new Thickness(10, 0, 10, 10);
			downloadButton.Padding = new Thickness(5);
			downloadButton.Id = "downloadButton";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(homeButton);
			verticalStackPanel1.Widgets.Add(downloadButton);

			
			Widgets.Add(verticalStackPanel1);
		}

		
		public ImageButton homeButton;
		public ImageButton downloadButton;
	}
}
