/* Generated by MyraPad at 1/27/2023 5:03:21 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace WakaSkies.Desktop.UI
{
	partial class NoticeHeader: Grid
	{
		private void BuildUI()
		{
			noticeText = new Label();
			noticeText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			noticeText.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			noticeText.Id = "noticeText";

			closeButton = new TextButton();
			closeButton.Text = "Close";
			closeButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			closeButton.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			closeButton.GridColumn = 1;
			closeButton.Background = new SolidBrush("#0379FF9D");
			closeButton.OverBackground = new SolidBrush("#026EE89D");
			closeButton.Id = "closeButton";

			
			ShowGridLines = true;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 20,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			Height = 40;
			Background = new SolidBrush("#0379FF9D");
			Id = "noticeHeader";
			Widgets.Add(noticeText);
			Widgets.Add(closeButton);
		}

		
		public Label noticeText;
		public TextButton closeButton;
	}
}
