/* Generated by MyraPad at 1/28/2023 4:27:57 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace WakaSkies.Desktop.UI
{
	partial class NoticeWindow: Window
	{
		private void BuildUI()
		{
			contentLabel = new Label();
			contentLabel.Wrap = true;
			contentLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			contentLabel.Id = "contentLabel";

			closeButton = new TextButton();
			closeButton.Text = "Close";
			closeButton.Margin = new Thickness(5);
			closeButton.Padding = new Thickness(5);
			closeButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			closeButton.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			closeButton.Id = "closeButton";

			var panel1 = new Panel();
			panel1.Widgets.Add(contentLabel);
			panel1.Widgets.Add(closeButton);

			
			Title = "";
			Left = 568;
			Top = 237;
			Width = 300;
			Height = 150;
			Content = panel1;
		}

		
		public Label contentLabel;
		public TextButton closeButton;
	}
}
