/* Generated by MyraPad at 1/25/2023 8:18:34 AM */
namespace WakaSkies.Desktop.UI
{
	public partial class StartMenu
	{
		public StartMenu()
		{
			BuildUI();
            // select index 1 so that it is the previous year.
			// because the current year is still in progress!
            wakaYearCombo.SelectedIndex = 1;
        }
	}
}