/* Generated by MyraPad at 1/28/2023 1:01:07 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace WakaSkies.Desktop.UI
{
	partial class StartMenu: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "WakaTime API Key:";
			label1.Margin = new Thickness(0, 0, 15, 0);

			wakaKeyInput = new TextBox();
			wakaKeyInput.MinWidth = 300;
			wakaKeyInput.MaxWidth = 300;
			wakaKeyInput.Width = 300;
			wakaKeyInput.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			wakaKeyInput.Id = "wakaKeyInput";

			wakaUnsureButton = new TextButton();
			wakaUnsureButton.Text = "?";
			wakaUnsureButton.MinWidth = 25;
			wakaUnsureButton.MaxWidth = 25;
			wakaUnsureButton.MinHeight = 25;
			wakaUnsureButton.MaxHeight = 25;
			wakaUnsureButton.Margin = new Thickness(3, 0, 0, 0);
			wakaUnsureButton.Id = "wakaUnsureButton";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(wakaKeyInput);
			horizontalStackPanel1.Widgets.Add(wakaUnsureButton);

			var label2 = new Label();
			label2.Text = "WakaTime User Name:";
			label2.Margin = new Thickness(0, 0, 15, 0);

			wakaUserInput = new TextBox();
			wakaUserInput.MinWidth = 300;
			wakaUserInput.MaxWidth = 300;
			wakaUserInput.Id = "wakaUserInput";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Widgets.Add(label2);
			horizontalStackPanel2.Widgets.Add(wakaUserInput);

			var label3 = new Label();
			label3.Text = "Year:";

			var listItem1 = new ListItem();
			listItem1.Text = "2023";

			var listItem2 = new ListItem();
			listItem2.Text = "2022";

			var listItem3 = new ListItem();
			listItem3.Text = "2021";

			var listItem4 = new ListItem();
			listItem4.Text = "2020";

			var listItem5 = new ListItem();
			listItem5.Text = "2019";

			var listItem6 = new ListItem();
			listItem6.Text = "2018";

			var listItem7 = new ListItem();
			listItem7.Text = "2017";

			var listItem8 = new ListItem();
			listItem8.Text = "2016";

			var listItem9 = new ListItem();
			listItem9.Text = "2015";

			var listItem10 = new ListItem();
			listItem10.Text = "2014";

			var listItem11 = new ListItem();
			listItem11.Text = "2013";

			wakaYearCombo = new ComboBox();
			wakaYearCombo.Margin = new Thickness(15, 0, 0, 0);
			wakaYearCombo.Id = "wakaYearCombo";
			wakaYearCombo.Items.Add(listItem1);
			wakaYearCombo.Items.Add(listItem2);
			wakaYearCombo.Items.Add(listItem3);
			wakaYearCombo.Items.Add(listItem4);
			wakaYearCombo.Items.Add(listItem5);
			wakaYearCombo.Items.Add(listItem6);
			wakaYearCombo.Items.Add(listItem7);
			wakaYearCombo.Items.Add(listItem8);
			wakaYearCombo.Items.Add(listItem9);
			wakaYearCombo.Items.Add(listItem10);
			wakaYearCombo.Items.Add(listItem11);

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Widgets.Add(label3);
			horizontalStackPanel3.Widgets.Add(wakaYearCombo);

			generateStats = new CheckBox();
			generateStats.IsChecked = true;
			generateStats.Text = "Add Stats To Model (takes longer)  ";
			generateStats.TextPosition = Myra.Graphics2D.UI.ImageTextButton.TextPositionEnum.Left;
			generateStats.Id = "generateStats";

			errorText = new Label();
			errorText.Wrap = true;
			errorText.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			errorText.TextColor = ColorStorage.CreateColor(255, 94, 110, 255);
			errorText.MaxWidth = 400;
			errorText.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			errorText.Visible = false;
			errorText.Id = "errorText";

			generateButton = new TextButton();
			generateButton.Text = "Generate Model!";
			generateButton.PressedBackground = new SolidBrush("#4242A6FF");
			generateButton.Height = 45;
			generateButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			generateButton.Background = new SolidBrush("#5756D5FF");
			generateButton.OverBackground = new SolidBrush("#4F4FC4FF");
			generateButton.Id = "generateButton";

			
			Spacing = 12;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Padding = new Thickness(15);
			Background = new SolidBrush("#00000080");
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalStackPanel2);
			Widgets.Add(horizontalStackPanel3);
			Widgets.Add(generateStats);
			Widgets.Add(errorText);
			Widgets.Add(generateButton);
		}

		
		public TextBox wakaKeyInput;
		public TextButton wakaUnsureButton;
		public TextBox wakaUserInput;
		public ComboBox wakaYearCombo;
		public CheckBox generateStats;
		public Label errorText;
		public TextButton generateButton;
	}
}
